CREATE DATABASE IF NOT EXISTS book;
USE book;

CREATE TABLE IF NOT EXISTS BOOK
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR(100) NOT NULL,
    PRICE        FLOAT NOT NULL,
    QTY          INT NOT NULL,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP

);
